package com.tim.vpnprotocols.compose.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4E54B5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E0FF)
val md_theme_light_onPrimaryContainer = Color(0xFF01006E)
val md_theme_light_secondary = Color(0xFF5C5C74)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE1E0FD)
val md_theme_light_onSecondaryContainer = Color(0xFF181A2E)
val md_theme_light_tertiary = Color(0xFF7B516C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8ED)
val md_theme_light_onTertiaryContainer = Color(0xFF300F27)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE4E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF777680)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inverseOnSurface = Color(0xFFF3EFF4)
val md_theme_light_inversePrimary = Color(0xFFBFC2FF)

val md_theme_dark_primary = Color(0xFFBFC2FF)
val md_theme_dark_onPrimary = Color(0xFF1C2085)
val md_theme_dark_primaryContainer = Color(0xFF353B9C)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E0FF)
val md_theme_dark_secondary = Color(0xFFC5C4E0)
val md_theme_dark_onSecondary = Color(0xFF2D2F44)
val md_theme_dark_secondaryContainer = Color(0xFF44455C)
val md_theme_dark_onSecondaryContainer = Color(0xFFE1E0FD)
val md_theme_dark_tertiary = Color(0xFFECB7D6)
val md_theme_dark_onTertiary = Color(0xFF48243D)
val md_theme_dark_tertiaryContainer = Color(0xFF613A54)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8ED)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_theme_dark_outline = Color(0xFF918F9A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inverseOnSurface = Color(0xFF303034)
val md_theme_dark_inversePrimary = Color(0xFF4E54B5)


val seed = Color(0xFF585EC0)
