name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build sample apk
      run: ./gradlew sample:assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apks
        path: sample/build/outputs/apk/release/*.apk

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.GPG_SIGNING_KEY }}
        SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
        run: |
           echo $ENCODED_STRING > keystore-b64.txt
           base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH
      
    - name: Publish
      run: ./gradlew publishReleasePublicationToMavenCentralRepository
      env:
          mavenUsername: ${{ secrets.MAVEN_USERNAME }}
          mavenPassword: ${{ secrets.MAVEN_PASSWORD }}
          signingKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
          signingKey: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          signingPassword: ${{ secrets.GPG_PASSWORD }}
